# Generated by Django 6.1.1 on 2026-09-08 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='学籍番号')),
                ('name', models.CharField(max_length=100, verbose_name='学生氏名')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='学科・コース')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生一覧',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='依頼件名')),
                ('description', models.TextField(verbose_name='依頼内容')),
                ('priority', models.CharField(choices=[('high', '高'), ('mid', '中'), ('low', '低')], default='mid', max_length=10, verbose_name='優先度')),
                ('status', models.CharField(choices=[('open', '未対応'), ('in_progress', '対応中'), ('closed', '完了')], default='open', max_length=20, verbose_name='ステータス')),
                ('privacy', models.CharField(choices=[('general', '一般（学内共有可）'), ('sensitive', '機密（関係部署のみ）')], default='general', max_length=20, verbose_name='プライバシー区分')),
                ('due_date', models.DateField(verbose_name='対応期日')),
                ('completion_note', models.TextField(blank=True, null=True, verbose_name='対応メモ（クローズ時）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='起票日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='個別担当者')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='起票者')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.student', verbose_name='対象学生')),
                ('target_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_tasks', to='auth.group', verbose_name='担当部署')),
            ],
            options={
                'verbose_name': 'タスク',
                'verbose_name_plural': 'タスク一覧',
                'ordering': ['due_date', '-priority'],
            },
        ),
    ]
