# Generated by Django 6.1.1 on 2026-09-08 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='申し送り内容・メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='記入日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='記入者')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.task', verbose_name='対象タスク')),
            ],
            options={
                'verbose_name': '対応メモ',
                'verbose_name_plural': '対応メモ履歴',
                'ordering': ['created_at'],
            },
        ),
    ]
