# Generated by Django 6.1.1 on 2026-09-09 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_taskcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['department', 'class_name', 'student_id'], 'verbose_name': '学生', 'verbose_name_plural': '学生一覧'},
        ),
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='クラス'),
        ),
        migrations.AddField(
            model_name='task',
            name='target_type',
            field=models.CharField(choices=[('student', '学生'), ('staff', '教職員')], default='student', max_length=10, verbose_name='対象種別'),
        ),
        migrations.AddField(
            model_name='task',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_tasks', to=settings.AUTH_USER_MODEL, verbose_name='対象教職員'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='学科'),
        ),
        migrations.AlterField(
            model_name='task',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.student', verbose_name='対象学生'),
        ),
    ]
