# Generated by Django 6.1.1 on 2026-09-09 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0003_alter_student_options_student_class_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='担当業務名')),
                ('department_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='auth.group', verbose_name='所属部・課')),
            ],
            options={
                'verbose_name': '担当業務',
                'verbose_name_plural': '担当業務一覧',
                'unique_together': {('department_group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='主所属（部・課）')),
                ('duties', models.ManyToManyField(blank=True, to='core.staffduty', verbose_name='担当業務（複数選択可）')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='教職員アカウント')),
            ],
            options={
                'verbose_name': '教職員プロファイル',
                'verbose_name_plural': '教職員プロファイル一覧',
            },
        ),
    ]
