# Generated by Django 6.1.1 on 2026-09-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_staffduty_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='is_on_leave',
            field=models.BooleanField(default=False, verbose_name='休暇中'),
        ),
    ]
