# Generated by Django 6.1.1 on 2026-09-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_staffprofile_is_on_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, help_text='チェックを外すとアプリの選択画面で非表示になります', verbose_name='ステータス（表示）'),
        ),
        migrations.AddField(
            model_name='student',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ニックネーム'),
        ),
    ]
