# Generated by Django 6.1.1 on 2026-09-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_student_is_active_student_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='furigana',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='フリガナ'),
        ),
    ]
