# Generated by Django 6.1.1 on 2026-09-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_student_furigana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='クラス'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='学科'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='ステータス（表示）'),
        ),
    ]
