# Generated by Django 6.1.1 on 2026-09-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_student_class_name_alter_student_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='student',
        ),
        migrations.AddField(
            model_name='task',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='core.student', verbose_name='対象学生'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='チェックを外すとアプリの選択画面で非表示になります', verbose_name='ステータス（表示）'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(db_index=True, verbose_name='対応期日'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', '高'), ('mid', '中'), ('low', '低')], db_index=True, default='mid', max_length=10, verbose_name='優先度'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', '未対応'), ('in_progress', '対応中'), ('closed', '完了')], db_index=True, default='open', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_type',
            field=models.CharField(choices=[('student', '学生'), ('staff', '教職員')], db_index=True, default='student', max_length=10, verbose_name='対象種別'),
        ),
    ]
