# Generated by Django 6.1.1 on 2026-09-10 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_task_student_task_students_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', '未対応'), ('in_progress', '対応中'), ('closed', '完了')], default='open', max_length=20, verbose_name='ステータス')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='個別メモ・進捗')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progresses', to='core.student', verbose_name='対象学生')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progresses', to='core.task', verbose_name='対象タスク')),
            ],
            options={
                'verbose_name': '学生別進捗',
                'verbose_name_plural': '学生別進捗一覧',
                'unique_together': {('task', 'student')},
            },
        ),
    ]
