# Generated by Django 6.1.1 on 2026-09-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_create_task_student_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='国籍'),
        ),
    ]
