# Generated by Django 6.1.1 on 2026-09-11 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_student_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='学科名')),
                ('order', models.PositiveIntegerField(default=0, help_text='数字が小さい順に並びます', verbose_name='表示順')),
            ],
            options={
                'verbose_name': '学科',
                'verbose_name_plural': '学科一覧',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例: HT-A, IT-Bなど', max_length=50, verbose_name='クラス名')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.department', verbose_name='所属学科')),
            ],
            options={
                'verbose_name': 'クラス',
                'verbose_name_plural': 'クラス一覧',
                'ordering': ['department__order', 'department__name', 'name'],
                'unique_together': {('department', 'name')},
            },
        ),
    ]
