# Generated by Django 6.1.1 on 2026-09-11 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_department_schoolclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'ordering': ['department__order', 'course__name', 'name'], 'verbose_name': 'クラス', 'verbose_name_plural': 'クラス一覧'},
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='コース名')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.department', verbose_name='所属学科')),
            ],
            options={
                'verbose_name': 'コース',
                'verbose_name_plural': 'コース一覧',
                'ordering': ['department__order', 'department__name', 'name'],
                'unique_together': {('department', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.course', verbose_name='所属コース'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('department', 'course', 'name')},
        ),
    ]
