# Generated by Django 6.1.1 on 2026-09-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_schoolclass_options_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['department', 'course', 'class_name', 'student_id'], 'verbose_name': '学生', 'verbose_name_plural': '学生一覧'},
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='コース'),
        ),
    ]
