# Generated by Django 6.1.1 on 2026-09-16 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_student_options_student_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['department__order', 'course__name', 'school_class__name', 'student_id'], 'verbose_name': '学生', 'verbose_name_plural': '学生一覧'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_name',
        ),
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.schoolclass', verbose_name='クラス'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.course', verbose_name='コース'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.department', verbose_name='学科'),
        ),
    ]
