# Generated by Django 6.1.1 on 2026-09-18 07:10

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0013_alter_user_last_name"),
        ("core", "0018_student_created_at_student_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentGroup",
            fields=[],
            options={
                "verbose_name": "所属部署",
                "verbose_name_plural": "所属部署一覧",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="staffduty",
            options={"verbose_name": "担当業務", "verbose_name_plural": "担当業務"},
        ),
        migrations.CreateModel(
            name="UserCompanion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "companion_type",
                    models.CharField(
                        choices=[
                            ("none", "未選択"),
                            ("chick", "ひよこ"),
                            ("robot", "ロボット"),
                            ("cactus", "サボテン"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="キャラクター種類",
                    ),
                ),
                (
                    "completed_tasks_count",
                    models.IntegerField(default=0, verbose_name="完了タスク数"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usercompanion",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "育成キャラクター",
                "verbose_name_plural": "育成キャラクター一覧",
            },
        ),
    ]
