# Generated by Django 6.1.1 on 2026-09-24 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_departmentgroup_alter_staffduty_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_archived",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="アーカイブフラグ"
            ),
        ),
        migrations.CreateModel(
            name="GraduatedCompanion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "companion_type",
                    models.CharField(
                        choices=[
                            ("none", "未選択"),
                            ("chick", "ひよこ"),
                            ("robot", "ロボット"),
                            ("cactus", "サボテン"),
                        ],
                        max_length=20,
                        verbose_name="キャラクター種類",
                    ),
                ),
                (
                    "completed_tasks_count",
                    models.IntegerField(default=0, verbose_name="卒業時完了タスク数"),
                ),
                (
                    "graduated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="殿堂入り日時"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graduated_companions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "殿堂入りキャラクター",
                "verbose_name_plural": "殿堂入りキャラクター一覧",
                "ordering": ["-graduated_at"],
            },
        ),
    ]
