# Generated by Django 6.1.1 on 2026-09-24 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0020_task_is_archived_graduatedcompanion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="target_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="group_tasks_m2m",
                to="auth.group",
                verbose_name="担当部署（複数）",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="target_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="targeted_tasks_m2m",
                to=settings.AUTH_USER_MODEL,
                verbose_name="対象教職員（複数）",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="is_archived",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="アーカイブ済み"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="target_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_tasks",
                to="auth.group",
                verbose_name="担当部署",
            ),
        ),
    ]
