# Generated by Django 6.1.1 on 2026-09-24 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_task_target_groups_task_target_users_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="reward_granted",
            field=models.BooleanField(default=False, verbose_name="報酬付与済み"),
        ),
        migrations.CreateModel(
            name="IslandItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("tree", "樹木 🌲"),
                            ("flower", "お花 🌸"),
                            ("rock", "大きな岩 🪨"),
                            ("house", "小さな家 🏠"),
                            ("fountain", "噴水 ⛲"),
                            ("shop", "お店 🏪"),
                            ("animal", "動物 🐶"),
                            ("castle", "お城 🏰"),
                        ],
                        max_length=50,
                        verbose_name="アイテム種類",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="アイテム名")),
                (
                    "position_x",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="配置位置X"
                    ),
                ),
                (
                    "position_y",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="配置位置Y"
                    ),
                ),
                (
                    "obtained_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="獲得日時"),
                ),
                (
                    "is_placed",
                    models.BooleanField(default=True, verbose_name="配置済み"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="island_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "島アイテム",
                "verbose_name_plural": "島アイテム一覧",
                "ordering": ["-obtained_at"],
            },
        ),
        migrations.CreateModel(
            name="IslandProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(default=1, verbose_name="島レベル")),
                ("experience", models.IntegerField(default=0, verbose_name="島経験値")),
                ("coins", models.IntegerField(default=0, verbose_name="コイン")),
                (
                    "gacha_tickets",
                    models.IntegerField(default=0, verbose_name="ガチャチケット"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="island_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "マイアイランド情報",
                "verbose_name_plural": "マイアイランド情報一覧",
            },
        ),
    ]
