# Generated by Django 6.1.1 on 2026-09-24 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_task_reward_granted_islanditem_islandprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="実績コード"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="実績名 / 称号名"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="説明"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TASK_COUNT", "タスク件数"),
                            ("STREAK", "継続日数"),
                            ("ISLAND_LEVEL", "島レベル"),
                            ("GACHA", "ガチャ回数"),
                            ("OTHER", "その他"),
                        ],
                        default="TASK_COUNT",
                        max_length=30,
                        verbose_name="カテゴリ",
                    ),
                ),
                (
                    "requirement_value",
                    models.IntegerField(default=1, verbose_name="達成必要値"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
            ],
            options={
                "verbose_name": "実績・称号",
                "verbose_name_plural": "実績・称号一覧",
                "ordering": ["category", "requirement_value", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="islandprofile",
            name="current_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.achievement",
                verbose_name="現在の称号",
            ),
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "achieved_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="達成日時"),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_achievements",
                        to="core.achievement",
                        verbose_name="実績",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_achievements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザー獲得実績",
                "verbose_name_plural": "ユーザー獲得実績一覧",
                "ordering": ["-achieved_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "achievement"), name="unique_user_achievement"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserTaskCompletionDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="タスク完了日")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_completion_dates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザー日別タスク完了記録",
                "verbose_name_plural": "ユーザー日別タスク完了記録一覧",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date"), name="unique_user_completion_date"
                    )
                ],
            },
        ),
    ]
