# Generated by Django 6.1.1 on 2026-09-24 08:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0023_achievement_islandprofile_current_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="部署実績コード"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="実績名 / 称号名"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="説明"),
                ),
                (
                    "requirement_type",
                    models.CharField(
                        choices=[
                            ("DEFEAT_COUNT", "討伐数"),
                            ("ALL_MEMBERS", "全員参加"),
                        ],
                        default="DEFEAT_COUNT",
                        max_length=30,
                        verbose_name="達成条件タイプ",
                    ),
                ),
                (
                    "requirement_value",
                    models.IntegerField(default=1, verbose_name="達成必要値"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
            ],
            options={
                "verbose_name": "部署実績・称号",
                "verbose_name_plural": "部署実績・称号一覧",
                "ordering": ["requirement_type", "requirement_value", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="DepartmentBattle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "boss_type",
                    models.CharField(
                        default="dragon", max_length=50, verbose_name="ボスの種類"
                    ),
                ),
                ("boss_name", models.CharField(max_length=100, verbose_name="ボス名")),
                ("max_hp", models.IntegerField(default=1000, verbose_name="最大HP")),
                (
                    "current_hp",
                    models.IntegerField(default=1000, verbose_name="現在HP"),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="開始日時"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="終了日時"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "進行中"),
                            ("defeated", "討伐完了"),
                            ("expired", "期限切れ"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battles",
                        to="auth.group",
                        verbose_name="対象部署",
                    ),
                ),
            ],
            options={
                "verbose_name": "部署ボス討伐",
                "verbose_name_plural": "部署ボス討伐一覧",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DepartmentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.departmentachievement",
                        verbose_name="現在の部署称号",
                    ),
                ),
                (
                    "department",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_profile",
                        to="auth.group",
                        verbose_name="部署",
                    ),
                ),
            ],
            options={
                "verbose_name": "部署プロファイル",
                "verbose_name_plural": "部署プロファイル一覧",
            },
        ),
        migrations.CreateModel(
            name="DepartmentAchievementUnlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unlocked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="達成日時"),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlocked_departments",
                        to="core.departmentachievement",
                        verbose_name="部署実績",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlocked_achievements",
                        to="auth.group",
                        verbose_name="部署",
                    ),
                ),
            ],
            options={
                "verbose_name": "部署獲得実績",
                "verbose_name_plural": "部署獲得実績一覧",
                "ordering": ["-unlocked_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("department", "achievement"),
                        name="unique_department_achievement",
                    )
                ],
            },
        ),
    ]
