# Generated by Django 6.1.1 on 2026-09-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_departmentachievement_departmentbattle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="islanditem",
            name="position_z",
            field=models.FloatField(default=0.0, verbose_name="配置位置Z"),
        ),
        migrations.AddField(
            model_name="islanditem",
            name="rotation_y",
            field=models.FloatField(default=0.0, verbose_name="Y軸回転"),
        ),
        migrations.AlterField(
            model_name="islanditem",
            name="position_x",
            field=models.FloatField(default=0.0, verbose_name="配置位置X"),
        ),
        migrations.AlterField(
            model_name="islanditem",
            name="position_y",
            field=models.FloatField(default=0.0, verbose_name="配置位置Y"),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("high", "高"),
                    ("mid", "中"),
                    ("medium", "中"),
                    ("low", "低"),
                ],
                db_index=True,
                default="mid",
                max_length=10,
                verbose_name="優先度",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "未着手"),
                    ("todo", "未着手"),
                    ("in_progress", "対応中"),
                    ("closed", "完了"),
                    ("completed", "完了"),
                ],
                db_index=True,
                default="open",
                max_length=20,
                verbose_name="ステータス",
            ),
        ),
        migrations.AlterField(
            model_name="taskstudentprogress",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "未着手"),
                    ("in_progress", "対応中"),
                    ("closed", "完了"),
                ],
                default="open",
                max_length=20,
                verbose_name="ステータス",
            ),
        ),
    ]
