# Generated by Django 6.1.1 on 2026-09-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_islanditem_position_z_islanditem_rotation_y_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="islanditem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("tree", "樹木 🌲"),
                    ("palm_tree", "ヤシの木 🌴"),
                    ("broadleaf_tree", "広葉樹 🌳"),
                    ("cherry_tree", "桜の木 🌸"),
                    ("flower", "お花 🌸"),
                    ("flower_bed", "花壇 🌷"),
                    ("sunflower_cluster", "ヒマワリの群生 🌻"),
                    ("garden_light", "ガーデンライト 💡"),
                    ("bonfire", "かがり火 🔥"),
                    ("fountain", "噴水 ⛲"),
                    ("small_pond", "小さな池 💧"),
                    ("rock", "大きな岩 🪨"),
                    ("wooden_bench", "木製ベンチ 🪑"),
                    ("hammock", "ハンモック 🏕️"),
                    ("beach_parasol_set", "ビーチパラソル＆サマーベッド 🏖️"),
                    ("wood_deck", "ウッドデッキ 🪵"),
                    ("cafe_table_set", "カフェテーブルセット ☕"),
                    ("watchtower", "見張り台 🗼"),
                    ("cottage", "コテージ風の小屋 🏡"),
                    ("house", "小さな家 🏠"),
                    ("shop", "お店 🏪"),
                    ("castle", "お城 🏰"),
                    ("animal", "動物 🐶"),
                    ("shiba_inu", "シバイヌ（犬） 🐕"),
                    ("calico_cat", "三毛猫（猫） 🐈"),
                    ("white_rabbit", "白ウサギ 🐇"),
                    ("capybara", "カピバラ 🦫"),
                    ("penguin", "ペンギン 🐧"),
                    ("seagull", "小鳥（カモメ） 🕊️"),
                    ("parakeet", "小鳥（インコ） 🦜"),
                ],
                max_length=50,
                verbose_name="アイテム種類",
            ),
        ),
    ]
