# Generated by Django 6.1.1 on 2026-09-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_graduatedcompanion_companion_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentbattle",
            name="boss_level",
            field=models.IntegerField(default=1, verbose_name="ボスレベル"),
        ),
        migrations.AddField(
            model_name="departmentbattle",
            name="last_defeated_date",
            field=models.DateField(blank=True, null=True, verbose_name="最終討伐日"),
        ),
        migrations.AddField(
            model_name="departmentprofile",
            name="is_loop_mode",
            field=models.BooleanField(default=False, verbose_name="周回モード"),
        ),
        migrations.AddField(
            model_name="departmentprofile",
            name="last_defeated_date",
            field=models.DateField(blank=True, null=True, verbose_name="最終討伐日"),
        ),
        migrations.AlterField(
            model_name="departmentbattle",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "進行中"),
                    ("recess", "本日の討伐完了（休憩中）"),
                    ("defeated", "討伐完了"),
                    ("expired", "期限切れ"),
                ],
                db_index=True,
                default="active",
                max_length=20,
                verbose_name="ステータス",
            ),
        ),
    ]
