# Generated by Django 6.1.1 on 2026-09-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_departmentbattle_boss_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentbattle",
            name="defeated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="討伐日時"),
        ),
        migrations.AddField(
            model_name="departmentbattle",
            name="pending_damage",
            field=models.IntegerField(default=0, verbose_name="未反映のダメージ量"),
        ),
    ]
