# Generated by Django 6.1.1 on 2026-09-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_departmentbattle_defeated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="islanditem",
            name="price",
            field=models.IntegerField(default=50, verbose_name="購入価格（コイン）"),
        ),
    ]
